### ISSUE TITLE
revdump <class 'FileNotFoundError'> 

### ISSUE THREAD

**Issue by peace20162** [bowen-liu/GDriveRevisionDumper#1]
I got file that sharing from others with editor permission and I want to download all revision of it but it sent me this error. can you help me with this error?

**Comment by bowen-liu** [comment]
Hello,
Can you post a full stack trace of the error printed by Python, as well as the command you're using?
Thanks!

**Comment by peace20162** [comment]
![image](https://user-images.githubusercontent.com/47591499/95867245-23fbf300-0d93-11eb-86d4-b47b35a311b6.png)

**Comment by peace20162** [comment]
![image](https://user-images.githubusercontent.com/47591499/95867317-39711d00-0d93-11eb-9c22-2405e6a5a02d.png)

**Comment by peace20162** [comment]
![image](https://user-images.githubusercontent.com/47591499/95867366-47bf3900-0d93-11eb-82b8-7b21a3ddbb1d.png)

**Comment by bowen-liu** [comment]
The issue seems to be related to filename. I'm guessing the script had issues handling the long unicode characters.

Go to line 426 of main.py and try replacing the following:
`fileDLPath = os.path.join(os.getcwd(), fileName)`

with an simpler hardcoded name:
`fileDLPath = os.path.join(os.getcwd(), "download")`

Let me know if that works, thanks!

**Comment by peace20162** [comment]
it's work thank u.

**Comment by bowen-liu** [comment]
No problem! I'll consider changing the code later to try and handle these kind of edge cases better.
